### PR TITLE
Elasticsearch

### PR DESCRIPTION
**Pull request by jonathanglassman**
What
----

Expanded Elasticsearch section within Deploying Backing Services section of tech docs. This is an MVP and has spun off multiple other stories for investigation.

How to review
-------------

Describe the steps required to test the changes.

1. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected.
1. Manually check that any removed or renamed anchor tags are not in use ([linkchecker](https://github.com/linkcheck/linkchecker) doesn't do this).
1. Check that the content fulfils story https://www.pivotaltracker.com/story/show/154638140

Who can review
--------------

Anyone except Jon Glassman or Jonathan Matthews.

### CODE REVIEW

**Comment by jpluscplusm** [comment]
@keymon Whilst Aiven take backups, they're not exposed via the broker as far as I can see. Also, the nature of the data that a tenant "should" be holding in ES is the kind which can be recreated from their primary datastore relatively easily. Taking these together was why @jonathanglassman and I chose not to keep a backup/restore section in these docs.

As the broker stands right now, the only thing we could document is that (1 + 2 hours ago) backups exist, but it's a manual operation to use them in any way. Is that worth doing, given the non-primary-datastore nature of the service?

**Comment by keymon** [comment]
> Taking these together is why @jonathanglassman and I chose not to keep a backup/restore section in these docs.

My only concern is that the tenants might ask or wonder about it. @jonathanglassman let me know what you think, I am happy to merge this as it is.

**Comment by jonathanglassman** [comment]
After discussion with @keymon and @jpluscplusm have agreed to state:

Backups are not currently supported. As a non-primary datastore, we recommend that transferring your data from your primary datastore to ES is something that your app is capable of doing on demand.

**Comment by jonathanglassman** [comment]
@keymon see latest commit - ok to approve?

**Pull request merged**
