### PR TITLE
Update to latest version of template

### PR DESCRIPTION
**Pull request by 36degrees**
## What

- Revise highlight state for table of contents (https://github.com/alphagov/tech-docs-template/pull/93)
- Add footer (https://github.com/alphagov/tech-docs-template/pull/94)
- Tweak typography, mainly around relationship between headings and copy (https://github.com/alphagov/tech-docs-template/pull/95)
- Enable font smoothing in Firefox (https://github.com/alphagov/tech-docs-template/pull/95)
- Alter inline code styling (https://github.com/alphagov/tech-docs-template/pull/95)
- Simplify layout (https://github.com/alphagov/tech-docs-template/pull/99)

The equivalent diff in the template would be:
https://github.com/alphagov/tech-docs-template/compare/22f782e1519eba5d324698059e54b10a1168569e...master

## How to review

- Verify that files changed does not revert any modifications you may have made from the template
- Run `bundle exec middleman server`, check that everything looks fine on desktop and mobile breakpoints, and that there are e.g. no JS errors.

## Who can review

Any of the technical writers involved with the PaaS documentation or any of the PaaS team who are confident reviewing this.

I can talk people through the changes if useful.

### CODE REVIEW

**Comment by bleach** [comment]
I had a quick look at this and it seems to render ok locally. 

I also tried to verify that it hasn't reverted any local modifications, but couldn't work out how to tell what we'd modified with any great confidence.

So I think this needs scheduling as work. Are there any significant upsides to upgrading or downsides to not upgrading that we should know about to prioritise this?

**Comment by 36degrees** [comment]
In this case, the biggest change is probably the addition of a footer, as no license or copyright is currently being displayed for the PaaS docs. However there are a number of other improvements detailed in the opening comment, which are based on feedback we've had from the technical writers.

I probably should have been clearer on the verifying accidental reversions point – I'm _pretty_ confident that nothing's been reverted – when running the update script conflicts like that are identified, and I didn't see any. So I think it's unlikely to happen (it would only occur if e.g. there was a bug in our update script).

One way you could verify the changes would be to compare your `master` branch to the template at `22f782e` – that's the commit hash of the previous version of the template used, found in `.template-version` on `master`.

```
$ paas-tech-docs git:(update-to-latest) git checkout master
  Switched to branch 'master'
  Your branch is behind 'origin/master' by 9 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ paas-tech-docs git:(master) git pull
  [..]
$ paas-tech-docs git:(master) cd ../tech-docs-template
$ tech-docs-template git:(master) git checkout 22f782e1519eba5d324698059e54b10a1168569e
  Note: checking out '22f782e1519eba5d324698059e54b10a1168569e'.

  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by performing another checkout.

  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -b with the checkout command again. Example:

    git checkout -b <new-branch-name>

  HEAD is now at 22f782e... Merge pull request #91 from alphagov/fix-code-block-padding
$ tech-docs-template git:(22f782e) cd -
  ~/Code/paas-tech-docs
$ paas-tech-docs git:(master) diff -qr source ../tech-docs-template/template/source
  Only in ../tech-docs-template/template/source: .DS_Store
  Only in source: documentation
  Only in source/images: actor.png
  Only in source/images: route-service.dot
  Only in source/images: route-service.png
  Only in source: index.html.md.erb
  Only in ../tech-docs-template/template/source/javascripts: .DS_Store
```

This shows that no files had previously changed against the template (otherwise you'd see for example `Files source/javascripts/modules/navigation.js and ../tech-docs-template/template/source/javascripts/modules/navigation.js differ`).

If you wanted to be *really* thorough (this is probably excessive), you could [diff between the old and new commit hash in `.template-version`](https://github.com/alphagov/tech-docs-template/compare/22f782e1519eba5d324698059e54b10a1168569e...734eb86a9b19fadd8e95f94f8a2586f2337961fc) and make sure that the changes made in this repo are the same.

It'd be great to understand how we can make this process as frictionless and painless as possible – in the long term we'd like to encourage teams to periodically update their _own_ docs against the template (without our team having to go around and open PRs) so that they get the latest changes.

(Sorry for the wall of text!)

**Comment by bleach** [comment]
Thanks for the detailed instructions @36degrees - definitely useful and hopefully something you can reuse in your docs or link to in other PRs.

**Comment by bleach** [comment]
A couple of things I've noticed. Are they intentional?

## Heading now wraps. 

### Before:

screen shot 2017-03-28 at 11 17 06

### After:

screen shot 2017-03-28 at 11 16 18

## Horizontal rule between sections has gone.

### Before

screen shot 2017-03-28 at 11 17 45


### After

screen shot 2017-03-28 at 11 17 33

**Comment by dashouse** [comment]
@bleach Yes these changes were intentional, we wanted to bring it in line (as much as possible) with GOV.UK Elements typographic styles. We stripped out the thick section divider as the updated size and margins should be enough to convey the start of a new section.

**Comment by alext** [comment]
> We stripped out the thick section divider as the updated size and margins should be enough to convey the start of a new section.

Has this been tested with users? In user testing, we've seen some users getting a little confused by the docs being one big page, and I fear this won't help that.

I'd like to get input from @HollyRC on this.

**Comment by HollyRC** [comment]
Hello, I agree with Alex that our users do get confused by the fact the tech docs are all one page. The section divider does something to help with their confusion around this. 
If you'd like to go ahead anyway, can I suggest that we monitor this? Perhaps some members of your team could come to our next couple of lab days to monitor use of the docs?

**Pull request closed without merging**
