### PR TITLE
WIP add rust docs

### PR DESCRIPTION
**Pull request by 0atman**
WIP, finalizing 17/12/2020

What
----

Describe what you have changed and why.

How to review
-------------

Describe the steps required to test the changes.

1. Preview the content locally ([see README](https://github.com/alphagov/paas-tech-docs#preview)) and check that it renders as expected.
1. Manually check that any removed or renamed anchor tags are not in use ([linkchecker](https://github.com/linkcheck/linkchecker) doesn't do this).
1. …

Who can review
--------------

Describe who can review the changes. Or more importantly, list the people
that can't review, because they worked on it.

### CODE REVIEW

**Comment by gds-ahine** [comment]
Not familiar with some of the Rust specific things mentioned, but it reads ok to me. Only issue I encountered is a number of the links are returning a 404.

**Comment by 0atman** [comment]
@gds-ahine the links are relative to https://docs.cloud.service.gov.uk, as this is where the docs are compiled and published to. I've used the same link format as a sibling page, so we should be good there. Paas will correct me if I'm wrong there, hopefully.

**Comment by AP-Hunt** [comment]
Hi folks,

I'm don't think we'd accept a PR for the Rust buildpack docs on our tenant facing docs, since it isn't a buildpack we officially support. What do you think @LeePorte @markpeterbuckley?

**Comment by 0atman** [comment]
@AP-Hunt Clair suggested this'd be the best place for it, but perhaps didn't have the buildpack context.

Very happy to document this anywhere, or here with a warning that it's not an officially supported buildpack?

**Comment by 0atman** [comment]
Will document this elsewhere - thanks!

**Comment by pauldougan** [comment]
@0atman perhaps it might find a home in https://github.com/alphagov/paas-community which contains a number of examples of things

**Pull request closed without merging**
